const FilterListData = [
  {
    id: 1,
    name: '정렬',
    subTap: [
      {
        id: 1,
        tapId: 1,
        name: '역대 인기순',
        query: 'sort=-view',
      },
      {
        id: 2,
        tapId: 1,
        name: '최신순',
        query: 'sort=-create_at',
      },
    ],
  },
  {
    id: 2,
    name: '주거형태',
    subTap: [
      {
        id: 1,
        tapId: 2,
        name: '원룸&오피스텔',
        query: 'housing-type=1',
      },
      {
        id: 2,
        tapId: 2,
        name: '아파트',
        query: 'housing-type=2',
      },
      {
        id: 3,
        tapId: 2,
        name: '빌라&연립',
        query: 'housing-type=3',
      },
      {
        id: 4,
        tapId: 2,
        name: '단독주택',
        query: 'housing-type=4',
      },
      {
        id: 5,
        tapId: 2,
        name: '사무공간',
        query: 'housing-type=5',
      },
      {
        id: 6,
        tapId: 2,
        name: '상업공간',
        query: 'housing-type=6',
      },
      {
        id: 7,
        tapId: 2,
        name: '기타',
        query: 'housing-type=7',
      },
    ],
  },
  {
    id: 3,
    name: '스타일',
    subTap: [
      {
        id: 1,
        tapId: 3,
        name: '모던',
        query: 'style=1',
      },
      {
        id: 2,
        tapId: 3,
        name: '북유럽',
        query: 'style=2',
      },
      {
        id: 3,
        tapId: 3,
        name: '빈티지',
        query: 'style=3',
      },
      {
        id: 4,
        tapId: 3,
        name: '내츄럴',
        query: 'style=4',
      },
      {
        id: 5,
        tapId: 3,
        name: '프로방스&로맨틱',
        query: 'style=5',
      },
      {
        id: 6,
        tapId: 3,
        name: '클래식&앤틱',
        query: 'style=6',
      },
      {
        id: 7,
        tapId: 3,
        name: '한국&아시아',
        query: 'style=7',
      },
      {
        id: 8,
        tapId: 3,
        name: '유니크',
        query: 'style=8',
      },
    ],
  },
  {
    id: 4,
    name: '평수',
    subTap: [
      {
        id: 0,
        tapId: 4,
        name: '1-10평대',
        query: 'min-size=1&max-size=10',
      },
      {
        id: 1,
        tapId: 4,
        name: '10평대',
        query: 'min-size=11&max-size=20',
      },
      {
        id: 2,
        tapId: 4,
        name: '20평대',
        query: 'min-size=21&max-size=30',
      },
      {
        id: 3,
        tapId: 4,
        name: '30평대',
        query: 'min-size=31&max-size=40',
      },
      {
        id: 4,
        tapId: 4,
        name: '40평대',
        query: 'min-size=41&max-size=50',
      },
      {
        id: 5,
        tapId: 4,
        name: '50평대',
        query: 'min-size=51&max-size=60',
      },
      {
        id: 6,
        tapId: 4,
        name: '60평대',
        query: 'min-size=61&max-size=70',
      },
      {
        id: 7,
        tapId: 4,
        name: '70평대',
        query: 'min-size=71&max-size=80',
      },
    ],
  },
  {
    id: 5,
    name: '컬러',
    subTap: [
      {
        id: 0,
        name: '배경',
        tapId: 5,
        tapColor: [
          {
            id: 1,
            tapId: 5,
            name: '배경 - 블랙',
            color: 'rgb(0,0,0)',
            query: 'back-color=1',
          },
          {
            id: 2,
            tapId: 5,
            name: '배경 - 화이트',
            color: 'rgb(255,255,255)',
            query: 'back-color=2',
          },
          {
            id: 3,
            tapId: 5,
            name: '배경 - 그레이',
            color: 'rgb(189,189,189)',
            query: 'back-color=3',
          },
          {
            id: 4,
            tapId: 5,
            name: '배경 - 베이지',
            color: 'rgb(244,231,197)',
            query: 'back-color=4',
          },
          {
            id: 5,
            tapId: 5,
            name: '배경 - 라이트 브라운',
            color: 'rgb(232,192,120)',
            query: 'back-color=5',
          },
          {
            id: 6,
            tapId: 5,
            name: '배경 - 브라운',
            color: 'rgb(100,65,52)',
            query: 'back-color=6',
          },
          {
            id: 7,
            tapId: 5,
            name: '배경 - 레드',
            color: 'rgb(213,55,54)',
            query: 'back-color=7',
          },
          {
            id: 8,
            tapId: 5,
            name: '배경 - 핑크',
            color: 'rgb(238,138,148)',
            query: 'back-color=8',
          },
          {
            id: 9,
            tapId: 5,
            name: '배경 - 옐로우',
            color: 'rgb(254,209,68)',
            query: 'back-color=9',
          },
          {
            id: 10,
            tapId: 5,
            name: '배경 - 그린',
            color: 'rgb(150,215,131)',
            query: 'back-color=10',
          },
          {
            id: 11,
            tapId: 5,
            name: '배경 - 민트',
            color: 'rgb(144,208,197)',
            query: 'back-color=11',
          },
          {
            id: 12,
            tapId: 5,
            name: '배경 - 블루',
            color: 'rgb(61,151,221)',
            query: 'back-color=12',
          },
          {
            id: 13,
            tapId: 5,
            name: '배경 - 네이비',
            color: 'rgb(34,62,95)',
            query: 'back-color=13',
          },
        ],
      },
      {
        id: 1,
        name: '소품',
        tapId: 6,
        tapColor: [
          {
            id: 1,
            tapId: 6,
            name: '소품 - 블랙',
            color: 'rgb(0,0,0)',
            query: 'item-color=1',
          },
          {
            id: 2,
            tapId: 6,
            name: '소품 - 화이트',
            color: 'rgb(255,255,255)',
            query: 'item-color=2',
          },
          {
            id: 3,
            tapId: 6,
            name: '소품 - 그레이',
            color: 'rgb(189,189,189)',
            query: 'item-color=3',
          },
          {
            id: 4,
            tapId: 6,
            name: '소품 - 베이지',
            color: 'rgb(244,231,197)',
            query: 'item-color=4',
          },
          {
            id: 5,
            tapId: 6,
            name: '소품 - 라이트 브라운',
            color: 'rgb(232,192,120)',
            query: 'item-color=5',
          },
          {
            id: 6,
            tapId: 6,
            name: '소품 - 브라운',
            color: 'rgb(100,65,52)',
            query: 'item-color=6',
          },
          {
            id: 7,
            tapId: 6,
            name: '소품 - 레드',
            color: 'rgb(213,55,54)',
            query: 'item-color=7',
          },
          {
            id: 8,
            tapId: 6,
            name: '소품 - 핑크',
            color: 'rgb(238,138,148)',
            query: 'item-color=8',
          },
          {
            id: 9,
            tapId: 6,
            name: '소품 - 옐로우',
            color: 'rgb(254,209,68)',
            query: 'item-color=9',
          },
          {
            id: 10,
            tapId: 6,
            name: '소품 - 그린',
            color: 'rgb(150,215,131)',
            query: 'item-color=10',
          },
          {
            id: 11,
            tapId: 6,
            name: '소품 - 민트',
            color: 'rgb(144,208,197)',
            query: 'item-color=11',
          },
          {
            id: 12,
            tapId: 6,
            name: '소품 - 블루',
            color: 'rgb(61,151,221)',
            query: 'item-color=12',
          },
          {
            id: 13,
            tapId: 6,
            name: '소품 - 네이비',
            color: 'rgb(34,62,95)',
            query: 'item-color=13',
          },
        ],
      },
    ],
  },
];

export default FilterListData;
